import React, { useState, useEffect } from 'react';
import { X, BookOpen, Sparkles, Share2, Copy, Check } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { useApp } from '../context/AppContext';
import { generateArticleContent } from '../services/aiService';
import { getAIApiKey } from '../services/authService';
import './ContentReaderModal.css';

export default function ContentReaderModal() {
  const context = useApp();
  const [isOpen, setIsOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [content, setContent] = useState('');
  const [title, setTitle] = useState('');
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    const handleOpen = async (e) => {
      const { topic, description } = e.detail;
      setTitle(topic);
      setIsOpen(true);
      setLoading(true);
      setError(null);
      setContent('');

      const apiKey = getAIApiKey();
      if (!apiKey) {
        setLoading(false);
        setError('Please add your Gemini API key in the Profile section to generate articles.');
        return;
      }

      try {
        const articleMd = await generateArticleContent(topic, description || '', context);
        setContent(articleMd);
      } catch (err) {
        console.error(err);
        setError('Failed to generate the content. Please try again later.');
      } finally {
        setLoading(false);
      }
    };

    window.addEventListener('openContentReader', handleOpen);
    return () => window.removeEventListener('openContentReader', handleOpen);
  }, [context]);

  const handleCopy = () => {
    if (!content) return;
    navigator.clipboard.writeText(title + '\\n\\n' + content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (!isOpen) return null;

  return (
    <div className="reader-overlay animate-fade-in" onClick={() => setIsOpen(false)}>
      <div className="reader-modal animate-scale-up" onClick={e => e.stopPropagation()}>
        
        {/* Header */}
        <div className="reader-header">
          <div className="reader-header__left">
            <div className="reader-icon-wrapper">
              <BookOpen size={20} color="white" />
            </div>
            <h2 className="reader-title">{title}</h2>
          </div>
          <div className="reader-header__actions">
            <button className="reader-action-btn" onClick={handleCopy} title="Copy to clipboard">
              {copied ? <Check size={18} className="text-mint" /> : <Copy size={18} />}
            </button>
            <button className="reader-close-btn" onClick={() => setIsOpen(false)}>
              <X size={20} />
            </button>
          </div>
        </div>

        {/* Content Area */}
        <div className="reader-content-area">
          {loading ? (
            <div className="reader-loading">
              <div className="reader-loading__orb">
                <Sparkles size={24} className="animate-spin-slow" />
              </div>
              <h3>Generating Personalized Insights...</h3>
              <p>Tailoring this topic to your career goals.</p>
              
              <div className="skeleton-wrapper">
                <div className="skeleton-line w-3/4"></div>
                <div className="skeleton-line w-full"></div>
                <div className="skeleton-line w-5/6"></div>
                <div className="skeleton-line w-full mt-4"></div>
                <div className="skeleton-line w-2/3"></div>
              </div>
            </div>
          ) : error ? (
            <div className="reader-error">
              <p>{error}</p>
            </div>
          ) : (
            <div className="reader-markdown">
              <ReactMarkdown>{content}</ReactMarkdown>
            </div>
          )}
        </div>

        {/* Footer */}
        {!loading && !error && (
          <div className="reader-footer">
            <p className="reader-footer__credits">Generated by Career OS AI ✨</p>
          </div>
        )}

      </div>
    </div>
  );
}
